# Arquivo de configuração da Netlify
[build]
  publish = "."
  command = ""

# Habilita o sistema de login da Netlify
[identity]
  url = "YOUR_SITE_URL" # Substituiremos isso depois

# Habilita as funções de backend
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  timeout = 30
