# Arquivo de configuração da Netlify
[build]
  publish = "."
  command = ""

# Habilita o sistema de login da Netlify
[identity]
  url = "YOUR_SITE_URL" # Substituiremos isso depois

# Habilita as funções de backend
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Configurações específicas para a NOSSA função
[functions."get-projetos"]
  # Aumenta o tempo limite desta função para 30s
  timeout = 30
