# Arquivo de configuração da Netlify
[build]
  publish = "."
  command = ""

# Habilita o sistema de login da Netlify
[identity]
  url = "YOUR_SITE_URL" # Substituiremos isso depois

# Habilita as funções de backend
[functions]
  directory = "netlify/functions"
  # LINHA NOVA: Diz ao Netlify como "empacotar" nosso código
_ node_bundler = "esbuild"
  # LINHA NOVA: Dá mais tempo para a UFPel responder
_ timeout = 30